#JWT
security:
  jwt:
    token:
      secret-key: CLEdutecno-SecretKey
      expire-length: 3600000

#DB en H2
#spring:
#  profiles:
#    active: dev
#  h2:
#    console:
#      enabled: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./data/M5_EXAMENFINAL_SistemaIMDb;DB_CLOSE_DELAY=-1
#    username: sa
#    password: password
#    initialization-mode: always
    #schema: classpath:import.sql
    #data: classpath:data.sql #File con data

#DB en MySQL
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/M5.EXAMENFINAL_SistemaIMDb"
    #url: "jdbc:mysql://localhost:3306/test"
    username: "root"
    password: "very_strong_password"
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: validate #validate #create #create-drop
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL8Dialect #Version 8 MySQL
    #database-platform: org.hibernate.dialect.MySQL5Dialect #Version 5 MySQL
    